### ISSUE TITLE
Criação do Roteiro da Entrevista

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#15]
Se deve criar um modelo com as perguntas que serão utilizadas na entrevista, o conjunto de perguntas deve contemplar as seguintes questões tomando com base a [Lista de funcionalidades do aplicativo](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/blob/main/Atividades/3%20Quinzena%20-%2024-04%20at%C3%A9%2007-05/Aplicativo.md):

1. Seção de funcionalidade
     - Peça para o usuário ordenar as funcionalidades, da mais relevante para a que é menos relevante.
     - Pergunte por que a funcionalidade que é mais relevante foi categorizada assim.
     - Pergunte por que a funcionalidade que é menos relevante foi categorizadas assim.
 2. Para o produto final 
     - Você valoriza a solução no geral? Não / Pouco / Médio / Muito
     - Por quê?
     - Em uma escala de 1 a 5, onde 1 é “eu nunca compraria este produto” e 5 é “eu definitivamente compraria este produto”, como você o avalia
     - Até quanto você estaria disposto a pagar por esse aplicativo?
  3. Qual parte dessa solução mais afeta você?
  4. O que você não precisa?
  5. Que funcionalidades estão faltando?
 
Com base nesses tópicos, se deve elaborar as perguntas que serão feitas as pessoas, bem como organizar as alternativas.

**Comment by Pedro-Emmanuel-G-C-Machado** [comment]
[Roteiro das Entrevistas de Projeto Interdisciplinar 02.pdf](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/files/15201623/Roteiro.das.Entrevistas.de.Projeto.Interdisciplinar.02.pdf)

**Comment by Pedro-Emmanuel-G-C-Machado** [comment]
Pronto agora acho que foi direitinho. Está aqui o PDF do roteiro das entrevistas.

**Comment by Erickjonatthan** [comment]
[Entrevista03.docx](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/files/15215190/Entrevista03.docx)
