### ISSUE TITLE
Criação de personas

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#16]
Utilizando o modelo de persona anexado aqui ou disponível na pasta da 3º quinzena, se deve elaborar uma persona que será usada na atividade

![Image](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/assets/94619256/40cd501c-e44c-49c9-9595-b71e46faf4c7)

**Comment by Erickjonatthan** [comment]
![Image](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/assets/65685466/cb3bf183-61e5-466a-8895-83b551058f4f)
