### ISSUE TITLE
Levantamento de funções de concorrentes

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#17]
Se deve elaborar uma listagem das principais funções de cada um dos concorrentes sugeridos na seção [Lista de funcionalidades do aplicativo](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/blob/main/Atividades/3%20Quinzena%20-%2024-04%20at%C3%A9%2007-05/Aplicativo.md)

## Lista de concorrentes diretos e indiretos

1. Google Chrome
2. Opera
3. Edge
4. Google tradutor

Idealmente, adicionem novos concorrentes principalmente focados na parte de tradução já que esse será o nosso principal diferencial

**Comment by gustavof0411** [comment]
Segue documento da pesquisa: 
https://docs.google.com/document/d/1TcVxYJ_tJqIInAj2XexY3auIEdPjIfuA3Et4_RY2DkE/edit?usp=sharing
