### ISSUE TITLE
Organização das correções da semana passada

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#18]
Tomando como base as atividades desenvolvidas nas quinzenas 2 e 3, organize as informações decorrente das 3 tecnologias para ser apresentadas ([Lista de Quinzenas](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/tree/main/Atividades)

Ajustar a exibição usando como base as criticas referentes a apresentação da quinzena 2 [[Lista de criticas](https://docs.google.com/spreadsheets/d/16ekLbAvapruJD-VMJbKoVNDBHu_rxxwuacEI4cveBpQ/edit#gid=342819701)]

**Comment by JMiguelsilva2003** [comment]
[passo a passo Midea PIpe.pdf](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/files/15211604/passo.a.passo.Midea.PIpe.pdf)


link vídeo da unreal
https://www.youtube.com/watch?v=QroghCR6CXc

link vídeo do easyOCR
https://www.youtube.com/watch?v=n-8oCPjpEvM&t=808s
