### ISSUE TITLE
Distribuição da escolha de problemas

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#2]
Listagem dos problemas ordenados já escolhidos:

1. Problema 4: Luana
-Erick
-Gustavo
-Pedro
-Miguel
-Vinicius

3. Problema 7: Lawrence
-Erick
-Douglas x 4

5. Problema 2: Ian
-Erick
-Pedro
-Miguel
-Vinicius
-Gladistony

7. Problema 3: Anny
-Gustavo
-Pedro
-Miguel
-Vinicius
-Gladistony

9. Problema 6: Severina
-Gustavo
-Pedro
-Miguel
-Vinicius
-Gladistony

**Comment by Gladistony** [comment]
Problema 4: Luana 
LUANA SOFRE COM A DIFICULDADE DE ENCONTRAR FILMES, SÉRIES E LIVROS ESPECÍFICOS, SEJA POR SEREM LANÇAMENTOS RECENTES OU POR ESTAREM RELACIONADOS A UM TEMA ESPECÍFICO, O QUE TRAZ PREJUÍZOS EM TERMOS DE MUITO TEMPO GASTO EM PESQUISAS INFRUTÍFERAS E FRUSTRAÇÃO POR NÃO ACESSAR O CONTEÚDO DESEJADO DE FORMA EFICIENTE.

Responsáveis: 
@Erickjonatthan @gustavof0411 @Pedro-Emmanuel-G-C-Machado @JMiguelsilva2003 @ViniciusHenrykyy 

Formato:
A tecnologia < tech > pode ajudar a resolver < prob > ao ultilizar a entrada < input > e devolver a saída < output >.

**Comment by Gladistony** [comment]
Problema 7: Lawrence
LAWRENCE SOFRE COM PROBLEMAS DE MEXER COM COMPUTADORES PQ NÃO SABE COMO USAR, LOCALIZAR DOCUMENTOS EM PASTAS E ACESSAR SITES, QUE TRAZ PREJUÍZOS COMO ACESSO RESTRITO À INFORMAÇÃO, COMUNICAÇÃO 
 COMPROMETIDA E DESVANTAGEM EDUCACIONAL PARA A SUA VIDA

Responsáveis: 
@Erickjonatthan @DouglasBezerra01 x 4

Formato:
A tecnologia < tech > pode ajudar a resolver < prob > ao ultilizar a entrada < input > e devolver a saída < output >.

**Comment by Gladistony** [comment]
Problema 2: Ian
IAN CURSA UMA FACULDADE EM TEMPO INTEGRAL E PRECISA PASSAR LONGOS PERÍODOS DE TEMPO INDO DE UMA CIDADE PARA OUTRA, ELE SOFRE COM O PROBLEMA DE NÃO TER TEMPO PARA FAZER SUAS ATIVIDADES E ESTUDAR E DEVIDO A ISSO  SEU DESEMPENHO ACADÊMICO É PREJUDICADO.

Responsáveis: 
@Erickjonatthan @Pedro-Emmanuel-G-C-Machado @JMiguelsilva2003 @ViniciusHenrykyy @Gladistony 

Formato:
A tecnologia < tech > pode ajudar a resolver < prob > ao ultilizar a entrada < input > e devolver a saída < output >.

**Comment by Gladistony** [comment]
Problema 3: Anny
ANNY SOFRE COM O PROBLEMA DE NÃO CONSEGUIR FOCAR NOS ESTUDOS E NÃO SABE COMO CONSEGUIR ESTUDAR 
 VÁRIAS MATÉRIAS DE UMA VEZ, QUE TRAZ OS PREJUÍZOS DE FALTA DE ATENÇÃO EM SALA, PERDA DE FOCO NOS ESTUDOS E
PROCRASTINAÇÃO QUE PREJUDICA O TEMPO DO SEU DIA A DIA NA SUA VIDA

Responsáveis: 
@gustavof0411 @Gladistony  @Pedro-Emmanuel-G-C-Machado @JMiguelsilva2003 @ViniciusHenrykyy 

Formato:
A tecnologia < tech > pode ajudar a resolver < prob > ao ultilizar a entrada < input > e devolver a saída < output >.

**Comment by Gladistony** [comment]
Problema 6: Severina
SEVERINA SOFRE COM O PROBLEMA DE TER ANALFABETISMO QUE TRAZ OS PREJUÍZOS DE IMPOSSIBILIDADE DE LER DE TEXTOS COTIDIANOS, COMO LIVROS OU NOME DE REMÉDIOS, PARA A SUA VIDA.

Responsáveis: 
@gustavof0411 @Gladistony  @Pedro-Emmanuel-G-C-Machado @JMiguelsilva2003 @ViniciusHenrykyy 

Formato:
A tecnologia < tech > pode ajudar a resolver < prob > ao ultilizar a entrada < input > e devolver a saída < output >.

**Comment by JMiguelsilva2003** [comment]
A realidade aumentada (AR) e realidade virtual (VR). Com essas tecnologias, Severina poderia resolver sua dificuldade de leitura ao receber como entrada informações de maneira visual e interativa de texto e devolver o texto em áudio com a explicação do mesmo facilitando a compreensão de conceitos complexos e até mesmo aprendendo a ler e escrever de maneira mais intuitiva.

**Comment by JMiguelsilva2003** [comment]
Para ajudar Anny a lidar com seus desafios de falta de foco nos estudos, procrastinação e dificuldade em estudar várias matérias ao mesmo tempo, podemos utilizar a Inteligência Artificial (IA)  recebendo como entrada os dados do assunto que ela estiver estudando para devolver uma Implementação de  um sistema de recompensas baseado em IA que motiva Anny a manter-se focada nos estudos e a alcançar seus objetivos de aprendizado.
