### ISSUE TITLE
Entrevista de pessoas

### ISSUE THREAD

**Issue by Erickjonatthan** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#21]
Usando o modelo de entrevista criado anteriormente, cada um deve escolher uma pessoa e fazer as respectivas perguntas para a mesma, anotar as respostas e enviar para a pasta do projeto

**Comment by Pedro-Emmanuel-G-C-Machado** [comment]
Aqui está a minha entrevista tanto em PDF como em  Docx 

[Entrevista de Projeto.docx](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/files/15209903/Entrevista.de.Projeto.docx)

**_Formato word(Docx)_**


[Entrevista de Projeto.pdf](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/files/15209904/Entrevista.de.Projeto.pdf)

**_PDF_**

**Comment by JMiguelsilva2003** [comment]
documento da entrevista 

[Entrevistador.docx](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/files/15211536/Entrevistador.docx)

vídeo

https://youtu.be/rwGh99bm454?si=rNYWcVIYVDUmXhJE

**Comment by Erickjonatthan** [comment]
Documento da entrevista:


[Entrevista03.docx](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/files/15215195/Entrevista03.docx)
