### ISSUE TITLE
Construção do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#26]
Pagina de Login/Registro
-Email e Senha para login
-Nome da pessoa, Curso, Email, Senha para cadastro

Pagina Principal
-Configuração de usuário
-Turmas cadastradas
-Forum para interação entre usuário
-Espaço de armazenamento pessoal para postar links públicos e armazenar dados
-Assistente de matricula
-Gerenciamento de turmas/monitoria

Configurações de usuário
-Enviar foto do perfil
-Período de ingresso
-Data de nascimento
-Endereço
-Nome da pessoa (não editável)
-Email (não editável) 

Turmas cadastradas
-Botão de adicionar nova turma
-Mostra as turmas cadastradas no semestre atual
---> Nas turmas você poderia ver quem está cadastrado, qual o professor e o monitor, o calendário da turma, avisos deixados pelo professor, horários de aula, monitoria e lista de exercícios. 

Forum da disciplina
-Separar os tópicos por disciplinas 
-Permitir aos usuários criar tópicos para tirar duvidas e responder as duvidas dos demais
-Gamificação com sistema de nível e tópicos  

Armazenamento
-Separa as pastas por tipo de arquivo e as matérias, além permitir facilmente a criação de links públicos

Gerenciamento de turmas
-Os professores poderão colocar notas privadas pra os alunos e marca eventos no calendários ou enviar atividades para a turma
-Os monitores terão acesso a uma ata de presença, enviar e resolver lista de exercícios.

As listas enviadas pelo monitor não mostram a resposta e desenvolvimento até que sejam marcadas para faze-lo pelo aluno.

**Comment by gustavof0411** [comment]
Ideias iniciais para as telas de login e cadastro. Não é a versão definitiva das telas nem as cores tema exibidas.

![Login](https://github.com/user-attachments/assets/7cb43599-b798-4260-b574-3dddbd65a5a3)

![Cadastro](https://github.com/user-attachments/assets/e80b3ddc-bdb8-4d49-98b4-97effbdc1b61)

**Comment by gustavof0411** [comment]
Ideias iniciais para a página inicial e a página de gerenciamento de perfil. Nada é definitivo por enquanto.

![Página Inicial](https://github.com/user-attachments/assets/f63fe53d-74dc-4ffb-935f-e5da32bc52bd)

![Gerenciar meu perfil (2)](https://github.com/user-attachments/assets/d7ab8567-0c73-40df-816e-341508b1a039)

**Comment by gustavof0411** [comment]
Ideias iniciais para o fórum (página) de uma disciplina. A logo exibida não é o nome oficial do aplicativo.

![Fórum de uma disciplina](https://github.com/user-attachments/assets/ac5b5456-2968-4c12-8797-b3a8e945ab4a)

Houveram algumas mudanças de cor na página inicial e gerenciamento de perfil, deixando a cor vermelha especificamente para a logo e para destaque de perfil de monitores e professores, enquanto a cor azul está relacionada com o tema geral do serviço (componentes e ícones). Essas mudanças ainda não são definitivas.

![Página Inicial](https://github.com/user-attachments/assets/a48d1901-ba91-4e0f-82eb-fa32f488344d)
![Gerenciar meu perfil](https://github.com/user-attachments/assets/74758d37-1b86-490b-8d04-688a99de300b)

**Comment by gustavof0411** [comment]
Ideias iniciais para a página de turmas cadastradas e suas respectivas páginas.

![Turmas cadastradas](https://github.com/user-attachments/assets/504317cc-614e-4de9-bf22-6d122f0abe52)

![Página de uma turma](https://github.com/user-attachments/assets/ed66e411-dca3-40a6-8215-0698b7dcc696)

**Comment by gustavof0411** [comment]
Tela de gerenciamento de arquivos.

![Meus arquivos](https://github.com/user-attachments/assets/a77d6dca-3dc9-4e7f-b12b-fb5e8ad901d9)

**Comment by gustavof0411** [comment]
Ideias iniciais para a tela de conversas.

<img width="2435" alt="Chats - Tela de início" src="https://github.com/user-attachments/assets/4de1eb7d-9498-4ca9-8aab-a5c136fd49d1">
<img width="2435" alt="Chats - Conversa aberta" src="https://github.com/user-attachments/assets/bce83b3a-367e-4655-8b74-fa455e3094c9">

**Comment by Gladistony** [comment]
Essa tarefa teve os prazos ajustados para o final da disciplina e ficará pausa até a conclusão do funcionamento básico de todas as funcionalidades do projeto
