### ISSUE TITLE
Criação de pagina de perfil de usuario

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#29]
Criar a pagina de perfil de usuário seguindo o modelo

**Comment by Erickjonatthan** [comment]
Já comecei, falta estilizar (mudar cor, botão, etc..) conforme o protótipo. Estou fazendo com bootstrap, se der problema é tranquilo passar para um arquivo css separado

**Comment by Erickjonatthan** [comment]
Página de perfil finalizada
