### ISSUE TITLE
1 - Problema 4: Luana

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#3]
Problema 4: Luana 
LUANA SOFRE COM A DIFICULDADE DE ENCONTRAR FILMES, SÉRIES E LIVROS ESPECÍFICOS, SEJA POR SEREM LANÇAMENTOS RECENTES OU POR ESTAREM RELACIONADOS A UM TEMA ESPECÍFICO, O QUE TRAZ PREJUÍZOS EM TERMOS DE MUITO TEMPO GASTO EM PESQUISAS INFRUTÍFERAS E FRUSTRAÇÃO POR NÃO ACESSAR O CONTEÚDO DESEJADO DE FORMA EFICIENTE.

Responsáveis: 
@Erickjonatthan @gustavof0411 @Pedro-Emmanuel-G-C-Machado @JMiguelsilva2003 @ViniciusHenrykyy 

Formato:
A tecnologia < tech > pode ajudar a resolver < prob > ao ultilizar a entrada < input > e devolver a saída < output >.

_Originally posted by @Gladistony in https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/issues/2#issuecomment-2052358696_

**Comment by Pedro-Emmanuel-G-C-Machado** [comment]
A tecnologia  uma rede neural onde a calibragem pode ser feita por sugestões e comportamentos anteriores, como por exemplo fazer um questionário e entender o tipo de gosto dos usuários, passando por séries, filmes, livros, temas gerais, autores e diretores, que a pessoa já gosta para poder entender o seu comportamento pode ajudar a resolver  a dificuldade para encontrar filmes, séries e livros específicos, seja por serem lançamentos recentes ou por estarem relacionados a um tema específico.  ao utilizar a entrada de quero novo filme, serie, livro, anime, mangá, história em quadrinhos e etc de um tema especifico, ou eu não sei o que assistir com a minha família e devolver a saída tenho a sugestão de tal filme, serie, história em quadrinhos ,  livro, fazendo o contexto geral da obra tanto para  situar a obra ao espectador,.

**Comment by Gladistony** [comment]
A tecnologia "Chat GPT" pode ajudar a resolver o problema de encontrar materiais ao utilizar a entrada parâmetros de gostos pessoais previamente cadastrados e devolver a saída sugestões condizentes com esses gostos, bem como locais onde encontrar esse conteúdo para assistir

**Comment by gustavof0411** [comment]
A tecnologia ChatGPT pode ajudar a resolver o problema de encontrar conteúdo ao utilizar a entrada de um questionário básico das preferências do usuário para avaliar por uma lista de mídias do IMDb e devolver a saída de indicação de possíveis conteúdos para assistir.

**Comment by ViniciusHenrykyy** [comment]
A tecnologia do Dongle: Dispositivos que transformam TVs comuns em smart TVs, permitindo acesso a serviços de streaming e aplicativos. Daria para ser ultilizada para estudar sobre o despositivo e criar a interfaces, layouts de pesquisas e etc...

**Comment by Erickjonatthan** [comment]
A tecnologia Inteligência Artificial Generativa pode ajudar a resolver o problema de encontrar conteúdo específico ao utilizar a entrada de preferências e histórico de pesquisa do usuário e devolver a saída de recomendações personalizadas e curadoria de conteúdo

**Comment by JMiguelsilva2003** [comment]
Para ajudar Luana a superar sua dificuldade em encontrar filmes, séries e livros específicos podemos usar IA para gerenciar o seu gosto, recebendo as suas preferências e obtendo dados de todo conteúdo assistido por ela para devolver como saída filmes que sejam de sua preferência.
