### ISSUE TITLE
Fazer as correções do html e otimizações dos codigos

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#33]
Verificar em todas as branchs as correções que serão preciso ser feitas no codigo html, php e javascript, além de auxiliar na construção das funcionalidades do projeto

**Comment by JMiguelsilva2003** [comment]
Correções na tela de login:
[Commit correção login](https://github.com/Gladistony/Aplicativo-Projeto-Interdisciplinar-2/commit/0c5233b6dcb58d2845b374c5dcb55af95c6d6db3)

**Comment by Gladistony** [comment]
Essa branch recebeu o conteúdo de todas as branchs separadas e então foi unida ao main
