### ISSUE TITLE
Construção/adaptação do bloco de menu de perfil

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#38]
Ajusta a formatação posterior a remoção do Bootstrap bem como organizar os calendários. Criar uma lista apropriada para os períodos tendo em vista que a uabj foi fundada em 2019 e que em teoria há 2 semestre por ano.

**Comment by Erickjonatthan** [comment]
Bootstrap removido e feature de responsividade para outros dispositivos

**Comment by Erickjonatthan** [comment]
Adicionado a lista de períodos
