### ISSUE TITLE
Ajuste da tela de Perfil

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#55]
A tela deve ser construída seguindo o padrão e reutilizando os designer das telas já prontas de: "top-menu.php", "menu-lateral.html" e "menu-conversas.php"
A construção deve ser realizada de movo que o conteúdo da tela fique nesse quadrado vermelho:

![Image](https://github.com/user-attachments/assets/a6bbef57-d9d1-4254-90dd-acbe2aad9a75)

Se deve refazer a tela para o novo formato reutilizando o otimizando os scripts já existentes.

**Comment by gustavof0411** [comment]
Descrição das alterações no commit.

Tela anterior:

![image](https://github.com/user-attachments/assets/61d6a390-d7a7-4d7b-bf07-3825594375b4)

Tela após as alterações:

![image](https://github.com/user-attachments/assets/1ad12f19-4774-4327-a003-38f6953907bf)
