### ISSUE TITLE
Criação da tela de arquivos

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#56]
A tela deve ser construída seguindo o padrão e reutilizando os designer das telas já prontas de: "top-menu.php", "menu-lateral.html" e "menu-conversas.php"
A construção deve ser realizada de movo que o conteúdo da tela fique nesse quadrado vermelho:

![Image](https://github.com/user-attachments/assets/a6bbef57-d9d1-4254-90dd-acbe2aad9a75)

Nessa tela deve-se incluir uma lista dos arquivos pessoas do usuário, um botão para o envio de arquivos de documento de texto ou imagens de um tamanho até X mb, e também uma opção para realizar o download desses arquivos.

**Comment by Erickjonatthan** [comment]
@Gladistony Cria minha branch please

**Comment by Gladistony** [comment]
Criada

**Comment by Erickjonatthan** [comment]
Pronto :)
