### ISSUE TITLE
Menu de arquivos

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#69]
Fazer a listagem dos arquivos na conta
Arrumar o box de exibição dos arquivos 
Fazer upload dos arquivos do servidor
Colocar um botão para download dos arquivos

**Comment by Erickjonatthan** [comment]
![Image](https://github.com/user-attachments/assets/ad1c26e4-9ec5-404d-b576-6ec14f12e858)
Assim ficou quando o usário não possui arquivo.

**Comment by Erickjonatthan** [comment]
![Image](https://github.com/user-attachments/assets/5143bab1-a22a-4ab7-9e0b-215b6737a0d8)
Assim ficou quando o usário possui algum arquivo

**Comment by Erickjonatthan** [comment]
![Image](https://github.com/user-attachments/assets/84669cef-ce3b-4be9-9bec-e47546c1942b)
Assim ficou quando clica em download, observe que ele não faz o dowload direto na máquina, isso requer mais estudo aprofundado para aplicar, se o usuário quiser fazer o download na máquina dele, basta fazer o download ao abrir o pdf na outra guia (se o doc for pdf) ou clicar com o botão direito, salvar como... (se o doc for imagem)

**Comment by Erickjonatthan** [comment]
![Image](https://github.com/user-attachments/assets/f778db3d-93cb-49a2-9f1e-cb09e8aa3c34)
Só para confirmar, os arquivos estão sendo passados para o firebase
