### ISSUE TITLE
Criar um perfil publico

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#74]
>Ter essas descrições: Nome, Curso, Cargo, Descrição, Data de criação do perfil, Período de ingresso, A pontuação e Nivel da pessoa no sistema game
>Botão de adicionar como amigo ou remover
>Lista de medalhas/conquistas

**Comment by gustavof0411** [comment]
Ideias iniciais para a tela de perfil de outro usuário.

<img width="3387" alt="Perfil de usuário" src="https://github.com/user-attachments/assets/4687d211-f31c-483a-896e-236c36804b1c">

**Comment by gustavof0411** [comment]
Progresso: tela de perfil público em código. 

![image](https://github.com/user-attachments/assets/73625be4-fe39-4a42-a388-8b45e95f8ec8)

**Comment by gustavof0411** [comment]
Progresso: tela de perfil público em código.

![image](https://github.com/user-attachments/assets/83456e1d-4483-4f18-851c-bed4198cd219)
