### ISSUE TITLE
Ajustes no Gerenciar Perfil

### ISSUE THREAD

**Issue by Gladistony** [Gladistony/Aplicativo-Projeto-Interdisciplinar-2#75]
Permitir editar o nome da pessoa
Adicionar a opção de editar a senha

**Comment by Erickjonatthan** [comment]
Ao clicar em editar perfil, agora o campo do nome do usuário ficará disponível para editar. Além disso, poderá alterar a senha também.

**Comment by Erickjonatthan** [comment]
![Image](https://github.com/user-attachments/assets/858b4a8e-e9ea-406d-ae8b-7f193451cfcf)

**Comment by Erickjonatthan** [comment]
Feat: adicionei um aviso que a senha deve conter 8 caracteres:
![Image](https://github.com/user-attachments/assets/24ca1e75-d861-4634-ae59-97cf2119dbae)

**Comment by Erickjonatthan** [comment]
Além disso, quando ele faz alguma alteração no perfil, para ser validada, ele faz logout
![Image](https://github.com/user-attachments/assets/5616a5bd-69bf-4fb1-90a6-e7539f97bf1b)

**Comment by Erickjonatthan** [comment]
Por fim, caso o usuário aperte para editar perfil e não tenha feito nenhuma alteração, volta ao estado normal da página

**Comment by Erickjonatthan** [comment]
Desso modo, finalizo o que foi pedido nessa tarefa. subindo commit
